# Generated by Django 5.0.7 on 2024-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('tecnology', models.CharField(max_length=100, verbose_name='tecnologia')),
                ('description', models.TextField(null=True, verbose_name='Descripción')),
                ('main_image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
